version: '3'

services:
  flask-app:
    build:
      context: ./flask
    ports:
      - "5000:5000"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=aman.json
    volumes:
      - ./flask:/app

  ui:
    build:
      context: ./UI
    ports:
      - "80:80"

